#!/usr/bin/env python3
"""
Wrap every generated neuron page (<model>/<layer>/<neuron>/vis.html) in the
shared GLUScope shell: stylesheet, breadcrumb navigation, and the shared
heat-map loader.

WHY THIS EXISTS
---------------
The vis.html pages are machine-generated by a script that does not live in this
repository. Regenerating them will overwrite everything this script does. So the
edits are kept deliberately small and mechanical -- head replaced, content
wrapped in <main>, trailing inline <script> swapped for a shared module -- and
this script is re-runnable so it can simply be applied again after a
regeneration. Better still, the ~10 lines of shell below can be folded into the
upstream generator, after which this script is no longer needed.

The generated content itself (headings, the summary table, the nested <details>
sections and the .circuit-viz placeholders) is passed through untouched. It is
restyled entirely from CSS.

IDEMPOTENT
----------
The shell is rebuilt from scratch on every run and the content region is
recognised in both its original and its already-wrapped form, so running this
twice is the same as running it once.

Usage:  python3 tools/apply-site-shell.py [--check]
          --check  report what would change, write nothing
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

SHELL = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <link rel="stylesheet" href="{root}assets/gluscope.css">
</head>
<body class="gs-neuron">
<div id="gs-nav"></div>
<main class="gs-container">
<noscript>This page needs JavaScript to draw the activation heat-maps and to
build the navigation bar. The summary statistics below are static.</noscript>
{content}
</main>
<script type="module" src="{root}assets/gluscope-nav.js"></script>
<script type="module" src="{root}assets/gluscope-viz.js"></script>
</body>
</html>
"""

# Start of the generated content: just inside <body>, past the shell's own
# wrapper if this page has already been processed.
CONTENT_START = re.compile(
    r"<body[^>]*>\s*"
    r'(?:<div id="gs-nav"></div>\s*)?'
    r'(?:<main class="gs-container">\s*)?'
    r"(?:<noscript>.*?</noscript>\s*)?",
    re.DOTALL,
)

# End of the generated content: the original trailing inline module script
# (preceded by an <hr> we drop), or our own </main> on a processed page.
CONTENT_END = re.compile(r"\s*(?:<hr\s*/?>\s*)?(?:<script type=\"module\">|</main>)")


def shell_for(path: pathlib.Path):
    """(title, relative path back to the site root) for a neuron page."""
    rel = path.relative_to(ROOT)
    model, layer, neuron = rel.parts[0], rel.parts[1], rel.parts[2]
    root = "../" * (len(rel.parts) - 1)
    return f"{model} · {layer} · {neuron} · GLUScope", root


def transform(path: pathlib.Path, src: str) -> str:
    start = CONTENT_START.search(src)
    if not start:
        raise ValueError("no <body> found")
    end = CONTENT_END.search(src, start.end())
    if not end:
        raise ValueError("could not find the end of the generated content "
                         "(no trailing module <script> and no </main>)")

    content = src[start.end():end.start()].strip()

    # Guard against silently emptying a page.
    if "circuit-viz" not in content:
        raise ValueError("content region contains no .circuit-viz placeholders")
    if "<h1>" not in content:
        raise ValueError("content region contains no <h1>")
    if "<script" in content:
        raise ValueError("content region still contains a <script>; the end "
                         "marker matched in the wrong place")

    title, root = shell_for(path)
    return SHELL.format(title=title, root=root, content=content)


def main():
    check = "--check" in sys.argv[1:]

    pages = sorted(
        p for p in ROOT.glob("*/*/*/vis.html")
        if not p.relative_to(ROOT).parts[0].startswith((".", "assets", "tools", "test"))
    )
    if not pages:
        sys.exit("apply-site-shell: no neuron pages found; is the layout "
                 "still <model>/<layer>/<neuron>/vis.html?")

    changed = unchanged = 0
    failures = []

    for page in pages:
        src = page.read_text(encoding="utf-8")
        try:
            out = transform(page, src)
        except ValueError as exc:
            failures.append((page.relative_to(ROOT), str(exc)))
            continue
        if out == src:
            unchanged += 1
        else:
            changed += 1
            if not check:
                page.write_text(out, encoding="utf-8")

    for rel, msg in failures:
        print(f"  SKIPPED {rel}: {msg}")

    verb = "would change" if check else "rewritten"
    print(f"  {len(pages)} neuron pages: {changed} {verb}, "
          f"{unchanged} already current, {len(failures)} skipped")

    if failures:
        sys.exit(f"apply-site-shell: {len(failures)} page(s) could not be "
                 f"processed; nothing about them was changed.")


if __name__ == "__main__":
    main()
